name = "Beautiful Penguin"
license = "MIT"
licenselink = "https://github.com/flypenguin/hugo-theme-beautifulpenguin/blob/master/LICENSE"
description = "An adaptation of the Beautiful Hugo theme which is an adaption of the Beautiful Jekyll theme"
tags = ["blog", "company", "portfolio", "projects", "minimal", "responsive", "seo", "google analytics", "bootstrap", "disqus", "light", "syntax highlighting", "multilingual", "portfolio", "projects", "mobile", "technical"]
features = ["blog", "remark42", "company", "portfolio", "projects", "minimal", "responsive", "seo", "google analytics", "bootstrap", "disqus", "light", "syntax highlighting", "multilingual", "portfolio", "projects", "mobile", "technical"]
min_version = 0.81

[author]
name = "flypenguin"
homepage = "http://flypenguin.de"

# If Porting existing theme
[original]
author =  "dattali"
homepage = "http://deanattali.com/beautiful-jekyll/"
repo = "https://github.com/daattali/beautiful-jekyll"
